### ISSUE TITLE
clean logic code.

### ISSUE THREAD

**Issue by bboyadao** [bbmokhtari/django-translations#56]
`File` “.../lib/python3.6/site-packages/translations/management/commands/synctranslations.py", line 76, in get_obsolete_translations
    if issubclass(model, Translatable):
TypeError: issubclass() arg 1 must be a class

```python3
def get_obsolete_translations(self, content_types):
        r"""Return the obsolete translations of some `ContentType`\ s."""
        if content_types:
            query = Q()
            for content_type in content_types:                                
                model = content_type.model_class()
                if issubclass(model, Translatable):
                    trans_fields = model._get_translatable_fields_names()
                    model_query = (
                        Q(content_type=content_type)
                        &
                        ~Q(field__in=trans_fields)
                    )
    
````

Take care about NoneType

I have a model created before. Then no longer use it.
i had 3hours to find out
hope this help!

**Comment by bbmokhtari** [comment]
Hey there.

> I have a model created before. Then no longer use it.

One question. Have you removed the `contenttypes` app from the installed apps?

**Comment by bboyadao** [comment]
Yes i found and removed it.

**Comment by bbmokhtari** [comment]
In that case, it's not supposed to work, as `contenttypes` is a *Django Translations v1* dependency. This dependency will be removed in version 2 though.
