### ISSUE TITLE
Error with relation to models without id

### ISSUE THREAD

**Issue by kamontat** [bbmokhtari/django-translations#57]
**Describe the bug**
Error when call 

**To Reproduce**
1. Create a model
2. Create a relational model (M2M)
3. Relational must have a custom primary key
```python
name = models.CharField(max_length=50, primary_key=True)
```
4. call translate with `qs.translate(...).translate_related(...)`

**Expected behavior**
relational models have been translated

**Screenshots**
![cleanshot 2019-03-02 at 12 29 45](https://user-images.githubusercontent.com/14089557/53677722-09245a00-3ce7-11e9-9e0e-36e7db1328d6.png)

**Desktop (please complete the following information):**
 - OS: `MacOS 10.14.3 (18D109)`
 - Browser: `Chrome Version 73.0.3683.46 (Official Build) beta (64-bit)`
 - Version `django-translations==1.1.0`

**Additional context**
I think it occurred because of this https://github.com/bbmokhtari/django-translations/blob/707502196a63741914db860c0fa8be9d79cbee43/translations/utils.py#L163

**Comment by bbmokhtari** [comment]
Hey @kamontat 

Thanks for submitting this bug report, I will check it out and let you know if it's actually a bug and if so when it will be fixed.

Best

**Comment by bbmokhtari** [comment]
This bug is fixed in the version `1.1.1`. Please upgrade your package to this version.
