### ISSUE TITLE
How can I check if a translated field exists (is filled) for specific language?

### ISSUE THREAD

**Issue by xupisco** [bbmokhtari/django-translations#59]
This is probably not thge better place to ask, but...

 - I have the field "name" on TranslatableMeta for the model.
 - I have three languages (pt, en and es)

How can I validate if the field is actually translated for some language?

**Comment by bbmokhtari** [comment]
you can query the [Translation](https://github.com/bbmokhtari/django-translations/blob/master/translations/models.py#L19) model in `translations.models.Translation`.
