### ISSUE TITLE
Unable to delete field translation

### ISSUE THREAD

**Issue by danpalmer** [bbmokhtari/django-translations#63]
**Describe the bug**

To my knowledge, there is no way to delete a translation for a single field, or to save the original value back over the top of it.

**Steps attempted:**
- Setting the field to `None` within a context.
- Calling `delattr` within a context.
- Setting the field to the original non-translated value.

None of these remove the translation of that field.

There are mechanisms to delete all of the translations relating to a model, but given that translations are on a per-field basis, this creates a mismatch that is hard to work around in custom tooling.

**Expected behavior**
At the very least, setting a field to the non-translated value should "work", updating the translation to the same value. Ideally this would _actually_ delete the translation, or an API is provided to delete the translation for a given field.

**Comment by AlphaJuliettOmega** [comment]
delete the fk referenced row?

Translatable -> Translation[]

delete translation = delete Translation

**Comment by bbmokhtari** [comment]
You can use the [Translation](https://github.com/bbmokhtari/django-translations/blob/253e7728439b1bab9bc57a5001b8d197509566ea/translations/models.py#L19) model as @AlphaJuliettOmega  mentioned.
