### ISSUE TITLE
Use Translatable as Mixin or Postgis support?

### ISSUE THREAD

**Issue by cddumanov** [bbmokhtari/django-translations#66]
Currently, I use PostGIS and GeoDjango. This requires to inherit model from `from django.contrib.gis.db import models.Model`. However, I want to use `Translatable` too but seems like it's impossible to combine them, right? Thanks

**Comment by bbmokhtari** [comment]
I have no idea cause I never tried this.

But I'm afraid I'm not planning to support the feature you described in the future either.
