### ISSUE TITLE
Unsupported lookup 'unaccent'

### ISSUE THREAD

**Issue by xupisco** [bbmokhtari/django-translations#67]
Can't use postgres `unaccent` extension on TranslatableQueryset

```
Unsupported lookup 'unaccent'
/translations/utils.py in _fill_dissected, line 78
```

My filter: (where qs in a TranslatableQueryset)
`qs = qs.filter(Q(name__unaccent__icontains=params.get('q')))`

Help?!

**Comment by bbmokhtari** [comment]
As described [here](https://github.com/bbmokhtari/django-translations/blob/253e7728439b1bab9bc57a5001b8d197509566ea/.github/README.md#compatibility) this project is not compatible with postgres (yet).
