### ISSUE TITLE
How to get all available translations to field?

### ISSUE THREAD

**Issue by ashkov** [bbmokhtari/django-translations#70]
I need to generate xml-file with all available translations of the field. How can I get them, without hardcode?

**Comment by bbmokhtari** [comment]
Each object from a `Translatable` model has a `translations` relation which you can use to retrieve all the translations available for that object.

``` python3
translatable_object.translations.all()
```

For more info, check this part of the documentation:
https://bbmokhtari.github.io/django-translations/_modules/translations/models.html#Translation
