### ISSUE TITLE
Updating translatable fields via DRF serializer

### ISSUE THREAD

**Issue by 4f3x** [bbmokhtari/django-translations#72]
Hey, is there a specific way you have to update the translatable model fields when using the DRF serializer? When updating through the `Context` object and the serializer's `.save()` method, the original values are mistakenly updated as well.

**Comment by 4f3x** [comment]
Until the authors provide their solution, this is my workaround in case anybody is having the same problem. If the user's language is the same as the default language, we can use the `.save()` method of the serializer. If this is not the case, we have to iterate over the `validated_data` items and update the initial object manually via `setattr()`:

```python
announcement = self.get_object()
serialized_edit = AnnouncementEditSerializer(announcement, data=request.data)
if serialized_edit.is_valid(raise_exception=True):
    if _get_default_language() == _get_active_language():
        announcement = serialized_edit.save()
    else:
        with Context(announcement) as context:
            for item in serialized_edit.validated_data.items():
                setattr(announcement, item[0], item[1])
            context.update()
```

**Comment by bbmokhtari** [comment]
It seems you have already figured it out, therefore I'm closing this issue.
Let me know if you have any more questions.
