### ISSUE TITLE
UnboundLocalError is raised by a queryset filtering by Exists

### ISSUE THREAD

**Issue by scottmx81** [bbmokhtari/django-translations#77]
**Describe the bug**

When filtering the queryset for a translatable model using `django.db.models.Exists` as the argument to filter, an `UnboundLocalError` is raised by `translations/query.py`. When the models are changed to inherit from `django.db.models.Model` directly instead of `translations.models.Translatable`, the queryset works as expected.

**To Reproduce**

1. Go to the sample project and upgrade Django to 3.0 with `pip install Django==3.0`
2. Go to the Django shell for the sample project with `python project/manage.py shell`
3. Run the following in the shell:
```
from django.db.models import Exists, OuterRef
from sample.models import Continent, Country
has_countries = Country.objects.filter(continent__pk=OuterRef('pk'))
Continent.objects.filter(Exists(has_countries))
```
4. You'll see an exception in the shell like this:
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/path/to/django-translations/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/path/to//django-translations/translations/querysets.py", line 82, in filter
    query = _fetch_translations_query_getter(
  File "/path/to/django-translations/translations/query.py", line 96, in _get_translations_query
    children[index] = q
UnboundLocalError: local variable 'q' referenced before assignment
```

**Expected behavior**

With Django 3.0+, and after changing the `Country` and `Continent` models in `sample/models.py` to inherit `models.Model` instead of `Translatable`, you will see the following:
```
>>> Continent.objects.filter(Exists(has_countries))
<QuerySet [<Continent: Europe>, <Continent: Asia>, <Continent: Africa>, <Continent: North America>, <Continent: South America>, <Continent: Australia>]>
>>>
```

Antarctica doesn't exist in the sample database but I would expect that this query would return successfully and filter out the continent of Antartica if it was added to the continents table but didn't have any countries associated with it.

**Desktop (please complete the following information):**

 - OS: macOS Big Sur (11.0.1)
 - Python 3.8.7
 - Django 3.0 +
 - Django Translations version 1.2.0

**Additional context**

This query does not appear to work on Django 2.x used in the sample project. But in Django 3+ it does what I expect.

```
>>> Continent.objects.create(name='Antarctica')
>>> Continent.objects.all()
<QuerySet [<Continent: Europe>, <Continent: Asia>, <Continent: Africa>, <Continent: North America>, <Continent: South America>, <Continent: Australia>, <Continent: Antarctica>]>
>>> Continent.objects.filter(Exists(has_countries))
<QuerySet [<Continent: Europe>, <Continent: Asia>, <Continent: Africa>, <Continent: North America>, <Continent: South America>, <Continent: Australia>]>
>>>
```

**Comment by bbmokhtari** [comment]
I'm going to drop support for Django versions less than 3.0 soon.
So I'm gonna ignore this bug since it works on those versions.
