### ISSUE TITLE
A database connection opened on start-up

### ISSUE THREAD

**Issue by alexivanov** [bbmokhtari/django-translations#80]
**Describe the bug**

The `TranslationsConfig.ready` method opens a database connection during start-up. This is behaviour is unexpected and [discouraged by Django](https://docs.djangoproject.com/en/3.2/ref/applications/#django.apps.AppConfig.ready).

**To Reproduce**

Run any management command & observer DB queries.

**Expected behaviour**

Is caching of content types on start-up necessary? The expected behaviour here is for `ready()` to not make any database queries.

**Additional context**

This affects all Django versions, though with `translations` in `INSTALLED_APPS` as per install instructions only >= 3.2 Django versions are affected (as `default_app_config` isn't set on the module so `TranslationsConfig` isn't used by default in < 3.2 Django versions).

**Comment by bbmokhtari** [comment]
Thank you for noticing and reporting.

Removed caching of content types in the commit `8a30902dc4e9ff84d83b376ec5d70e45118f41ae`.
