### ISSUE TITLE
cannot import name 'ugettext_lazy' from 'django.utils.translation'

### ISSUE THREAD

**Issue by summonerriftofficial** [bbmokhtari/django-translations#81]
cannot import name 'ugettext_lazy' from 'django.utils.translation'

**Comment by PeterJCLaw** [comment]
https://github.com/PeterJCLaw/django-translations/pull/2 hopes to help with this, pending a response from the maintainer.

**Comment by xcixor** [comment]
Is this completely abandoned?

**Comment by bbmokhtari** [comment]
This has been fixed in the library source code to:

```python3
try:
    from django.utils.translation import ugettext_lazy as _
except ImportError:
    from django.utils.translation import gettext_lazy as _
```

in order to remain backwards-compatible with older Django versions such as `2.2`.

Also the library has been updated recently to support Django up until version `5.1`.

@xcixor @PeterJCLaw @summonerriftofficial
