### ISSUE TITLE
Removing a field from a model cause "Exception Value: '<Model>' object has no attribute '<field>'" in TranslationInline

### ISSUE THREAD

**Issue by ashkov** [bbmokhtari/django-translations#85]
If the field **with some rows** in translations_translation table **was removed** from source of some model,
when we go to the admin with 

`inlines = [TranslationInline,]`

we will get this error
"Exception Value: 'Model' object has no attribute 'field'"
in 
https://github.com/bbmokhtari/django-translations/blob/e8f66710af9433044937b75c061e1988add398a5/translations/models.py#L53

**How to resolve**
I think, it is need to add condition to test if self.content_object has field self.field:

`source = getattr(self.content_object, self.field) if hasattr(self.content_object, self.field) else self.field
    `

**Comment by troyjfarrell** [comment]
This should probably not cause an exception, but it should log an error.

However, when the field was removed from the model, it would have been good to remove the translations as part of the migration.  That may have prevented this error.  I haven't figured out (yet) how to do this, but if I do, I'll post it here.

**Comment by bbmokhtari** [comment]
You gotta run `python manage.py synctranslations
`.

Look [here](https://github.com/bbmokhtari/django-translations/blob/253e7728439b1bab9bc57a5001b8d197509566ea/docs/guide/models.rst#changing-the-models-and-fields-configurations)
