### ISSUE TITLE
Postgres support

### ISSUE THREAD

**Issue by PeterJCLaw** [bbmokhtari/django-translations#87]
The project's README indicates that it's not compatible with PostgreSQL, however from experience it seems to in fact work ok. I'm not sure if I'm just not using all the features, but even then it might be useful to have details in the README about what's supported and what isn't.

Is there a record somewhere of what's known to be broken with PostgreSQL?

**Comment by troyjfarrell** [comment]
Some of the more complicated queries do not work in PostgreSQL with the current code.  One of the problems is documented in #65.  I have submitted a PR which fixes PostgreSQL support: #83.

**Comment by marcinowski** [comment]
👋Hello, is there any reason the fix isn't merged yet?

**Comment by bbmokhtari** [comment]
I'm working on this based off of the mentioned PR.
