### ISSUE TITLE
Unable to translate records with same foreign keys

### ISSUE THREAD

**Issue by abdulrehmansohail** [bbmokhtari/django-translations#92]
**Describe the bug**
I am trying to translate related fields of a model. but it only translated the first record and skipped  the ones which are repeating.

**To Reproduce**
1. create a model of Department with fields, department_name and their respective translations 
2. Create a model of employee with foreign key of department
3. create multiple employees with same department and translate them 
4. you can see issue 

**Expected behavior**
It should translate all the department names 

**Screenshots**
It should translate both the records with  430000000001 number 

![image](https://user-images.githubusercontent.com/71159866/215451556-c7fa03f3-49a1-440f-8da6-4b35353cc5f4.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 2020.04
 - Browser chrome

**Comment by bbmokhtari** [comment]
Translations don't apply to foreign keys they apply to the main model.

If you want department to be translatable you must make it (department) translatable and work with department values in contexts or querysets.

You can not work with employee to set the department translations.
